name: flutter_ecommerce_app
description: A new Flutter project discover project.
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  flutter_rating_bar: ^3.0.1+1
  smooth_star_rating: ^1.1.1
  font_awesome_flutter: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
